input_data_path: "data/heart.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
transformer_path: "models/transformer.pkl"
model: "RandomForestClassifier"
splitting_params:
  val_size: 0.3
  random_state: 42
feature_params:
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
    - "slope"
    - "ca"
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "thal"
  target_feature: "target"